### PR TITLE
Repeated serialization fails to add discriminator

### PR DESCRIPTION
**Pull request by ibebbs**
This PR resolves issue #22

I finally got a handle on the toggling of `_isInRead`/`_isInWrite` by reading [this answer](https://stackoverflow.com/a/57837893/628821) to a similar issue on StackOverflow. Turns out the way to resolve this issue was simply to leave the toggling in-place while adding the finally blocks I had outlined in the initial bug report.

Anyway, the amended code now passes all unit tests including my new "RepeatedSerialization" tests.

Could you let me know if you're likely to merge this PR any time soon? If not, I'll build a custom version of this package for use in my project.

Thanks, Ian

### CODE REVIEW

**Comment by dmitry-bym** [comment]
Hello @ibebbs, thanks for your pr and issue. Yes, i aprove this changes but i need to test it. I'll create new version asap i think it will be avaliable until the end of the week. Is it ok for you?

**Comment by ibebbs** [comment]
Hi Dmitry, great timing, I just sat down to build my own version of this package but won't need to now, end of the week is fine (although sooner the better ;0).

Hopefully there's not too much to test. The changes are minimal (just a try..finally really), pass all the existing unit tests and I've added a unit test to reproduce the issue I was experiencing which also now passes.

Thanks for a very useful library. Ian.

**Comment by dmitry-bym** [comment]
@ibebbs Hi, I wanted to release a new version, but i can't for now, You added a lot of changes, I think you wanted to do it locally

**Comment by ibebbs** [comment]
Hi @dmitry-bym, yes, I hadn't realised Equ didn't provide deep object equality and, as I am rather invested in (and impressed by) Equ now, I thought I'd add this capability via the `*Recursive` providers.

I'm happy to talk you through the changes in this PR. They're actually quite straight forward and most of the churn is refactoring previous changes to provide all the desired functionality.

I have packaged my changes into a [nuget](https://github.com/ibebbs/Equ/packages/640327) in [my fork](https://github.com/ibebbs/Equ) and am actively using it in a couple of projects. So far so good. If you feel the "recursive"/"deep" comparison capability is not a good fit for Equ, I am happy to continue using my fork.

**Comment by dmitry-bym** [comment]
Made it myself, will release asap

**Pull request closed without merging**
